# service name
spring:
  application:
    name: micr-dataservice
  # configure mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost3306/fintechdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1029594577Abc.

# configure mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml       # the class path of this configuration file, including all xml files
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true      # camel case mapping

# configure dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.celan.dataservice.service
  provider:
    timeout: 50000
    retries: 0
